#%RAML 0.8
title: MyTest
version: 1.0

/customers:
  displayName: This is a test API
  get:
    description: This is the description of test API
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

  